import json
import os

def load_ml_predictions(path="knowledge/ml_output.json"):
    """Loads prediction data from a JSON file generated by an ML model."""
    if not os.path.exists(path):
        print(f"⚠️ No ML prediction file found at: {path}")
        return {}

    try:
        with open(path, "r", encoding='utf-8') as file:
            return json.load(file)
    except Exception as e:
        print(f"❌ Failed to load ML prediction file: {e}")
        return {}
